IF "%NCH_JAVA_HOME%"=="" GOTO SET_JAVA_HOME ELSE (GOTO DONE)

:SET_JAVA_HOME

SET BIN_HOME=C:\TDE\bin
SET JAVA_VER=1.8.0_25

SET SBIN_HOME=%BIN_HOME%\sbin

SET NCH_JAVA_HOME=%SBIN_HOME%\java\jdk%JAVA_VER%
SET NCH_JAVA_EXE=%NCH_JAVA_HOME%\bin\java.exe
SET PATH=%NCH_JAVA_HOME%\\bin;%PATH%

SET GRADLE_HOME=%SBIN_HOME%\gradle\2.2.1
SET PATH=%GRADLE_HOME%\bin;%PATH%

REM SET ANT_HOME=%SBIN_HOME%\ant\1.9.4
REM SET PATH=%ANT_HOME%\bin;%PATH%

REM SET GROOVY_HOME=%SBIN_HOME%\groovy\2.3.7
REM SET PATH=%GROOVY_HOME%\bin;%PATH%

SET %JAVA_HOME%=%NCH_JAVA_HOME%

:DONE
